//could i do a 1 time for loop to get spec data for each class to populate a spec obj?

const specMedia = {
	263: "https://render.worldofwarcraft.com/us/icons/56/spell_shaman_improvedstormstrike.jpg",
	270: "https://render.worldofwarcraft.com/us/icons/56/spell_monk_mistweaver_spec.jpg",
	66: "https://render.worldofwarcraft.com/us/icons/56/ability_paladin_shieldofthetemplar.jpg",
	255: "https://render.worldofwarcraft.com/us/icons/56/ability_hunter_camouflage.jpg",
	256: "https://render.worldofwarcraft.com/us/icons/56/spell_holy_powerwordshield.jpg",
	268: "https://render.worldofwarcraft.com/us/icons/56/spell_monk_brewmaster_spec.jpg",
	72: "https://render.worldofwarcraft.com/us/icons/56/ability_warrior_innerrage.jpg",
	252: "https://render.worldofwarcraft.com/us/icons/56/spell_deathknight_unholypresence.jpg",
	259: "https://render.worldofwarcraft.com/us/icons/56/ability_rogue_deadlybrew.jpg",
	264: "https://render.worldofwarcraft.com/us/icons/56/spell_nature_magicimmunity.jpg",
	64: "https://render.worldofwarcraft.com/us/icons/56/spell_frost_frostbolt02.jpg",
	62: "https://render.worldofwarcraft.com/us/icons/56/spell_holy_magicalsentry.jpg",
	65: "https://render.worldofwarcraft.com/us/icons/56/spell_holy_holybolt.jpg",
	70: "https://render.worldofwarcraft.com/us/icons/56/spell_holy_auraoflight.jpg",
	71: "https://render.worldofwarcraft.com/us/icons/56/ability_warrior_savageblow.jpg",
	73: "https://render.worldofwarcraft.com/us/icons/56/ability_warrior_defensivestance.jpg",
	253: "https://render.worldofwarcraft.com/us/icons/56/ability_hunter_bestialdiscipline.jpg",
	254: "https://render.worldofwarcraft.com/us/icons/56/ability_hunter_focusedaim.jpg",
	258: "https://render.worldofwarcraft.com/us/icons/56/spell_shadow_shadowwordpain.jpg",
	261: "https://render.worldofwarcraft.com/us/icons/56/ability_stealth.jpg",
	103: "https://render.worldofwarcraft.com/us/icons/56/ability_druid_catform.jpg",
	104: "https://render.worldofwarcraft.com/us/icons/56/ability_racial_bearform.jpg",
	105: "https://render.worldofwarcraft.com/us/icons/56/spell_nature_healingtouch.jpg",
	267: "https://render.worldofwarcraft.com/us/icons/56/spell_shadow_rainoffire.jpg",
	257: "https://render.worldofwarcraft.com/us/icons/56/spell_holy_guardianspirit.jpg",
	63: "https://render.worldofwarcraft.com/us/icons/56/spell_fire_firebolt02.jpg",
	250: "https://render.worldofwarcraft.com/us/icons/56/spell_deathknight_bloodpresence.jpg",
	251: "https://render.worldofwarcraft.com/us/icons/56/spell_deathknight_frostpresence.jpg",
	260: "https://render.worldofwarcraft.com/us/icons/56/ability_rogue_waylay.jpg",
	262: "https://render.worldofwarcraft.com/us/icons/56/spell_nature_lightning.jpg",
	265: "https://render.worldofwarcraft.com/us/icons/56/spell_shadow_deathcoil.jpg",
	266: "https://render.worldofwarcraft.com/us/icons/56/spell_shadow_metamorphosis.jpg",
	269: "https://render.worldofwarcraft.com/us/icons/56/spell_monk_windwalker_spec.jpg",
	102: "https://render.worldofwarcraft.com/us/icons/56/spell_nature_starfall.jpg",
	577: "https://render.worldofwarcraft.com/us/icons/56/ability_demonhunter_specdps.jpg",
	581: "https://render.worldofwarcraft.com/us/icons/56/ability_demonhunter_spectank.jpg",
	1467: "https://render.worldofwarcraft.com/us/icons/56/classicon_evoker_devastation.jpg",
	1468: "https://render.worldofwarcraft.com/us/icons/56/classicon_evoker_preservation.jpg",
};

export default specMedia;
